import type { KeyframeTemplate } from '@/types';

export const SVG_KEYFRAME_TEMPLATES: KeyframeTemplate[] = [
  {
    id: 'fade-in-out',
    name: 'Fade In/Out',
    description: 'Smooth fade in then fade out',
    easing: 'ease-in-out',
    keyframes: [
      { time: 0, properties: { opacity: 0 } },
      { time: 0.3, properties: { opacity: 1 } },
      { time: 0.7, properties: { opacity: 1 } },
      { time: 1.0, properties: { opacity: 0 } },
    ],
  },
  {
    id: 'scale-bounce',
    name: 'Scale Bounce',
    description: 'Scale up with elastic bounce',
    easing: 'ease-out',
    keyframes: [
      { time: 0, properties: { scale: 0, opacity: 0 } },
      { time: 0.3, properties: { scale: 1.2, opacity: 1 } },
      { time: 0.5, properties: { scale: 0.9, opacity: 1 } },
      { time: 0.65, properties: { scale: 1.05, opacity: 1 } },
      { time: 0.8, properties: { scale: 1.0, opacity: 1 } },
      { time: 1.0, properties: { scale: 1.0, opacity: 1 } },
    ],
  },
  {
    id: 'slide-right',
    name: 'Slide Right',
    description: 'Slide in from left to right',
    easing: 'ease-out',
    keyframes: [
      { time: 0, properties: { translateX: -100, opacity: 0 } },
      { time: 0.4, properties: { translateX: 0, opacity: 1 } },
      { time: 0.8, properties: { translateX: 0, opacity: 1 } },
      { time: 1.0, properties: { translateX: 100, opacity: 0 } },
    ],
  },
  {
    id: 'slide-up',
    name: 'Slide Up',
    description: 'Slide in from bottom to top',
    easing: 'ease-out',
    keyframes: [
      { time: 0, properties: { translateY: 100, opacity: 0 } },
      { time: 0.4, properties: { translateY: 0, opacity: 1 } },
      { time: 0.8, properties: { translateY: 0, opacity: 1 } },
      { time: 1.0, properties: { translateY: -100, opacity: 0 } },
    ],
  },
  {
    id: 'rotate-360',
    name: 'Full Rotation',
    description: 'Continuous 360-degree rotation',
    easing: 'linear',
    keyframes: [
      { time: 0, properties: { rotate: 0, opacity: 1 } },
      { time: 1.0, properties: { rotate: 360, opacity: 1 } },
    ],
  },
  {
    id: 'pulse',
    name: 'Pulse',
    description: 'Rhythmic scale pulsing',
    easing: 'ease-in-out',
    keyframes: [
      { time: 0, properties: { scale: 1.0 } },
      { time: 0.25, properties: { scale: 1.15 } },
      { time: 0.5, properties: { scale: 1.0 } },
      { time: 0.75, properties: { scale: 1.15 } },
      { time: 1.0, properties: { scale: 1.0 } },
    ],
  },
  {
    id: 'float',
    name: 'Float',
    description: 'Gentle floating up and down',
    easing: 'ease-in-out',
    keyframes: [
      { time: 0, properties: { translateY: 0 } },
      { time: 0.25, properties: { translateY: -20 } },
      { time: 0.5, properties: { translateY: 0 } },
      { time: 0.75, properties: { translateY: 20 } },
      { time: 1.0, properties: { translateY: 0 } },
    ],
  },
  {
    id: 'spin-scale',
    name: 'Spin & Scale',
    description: 'Rotate while scaling in and out',
    easing: 'ease-in-out',
    keyframes: [
      { time: 0, properties: { rotate: 0, scale: 0, opacity: 0 } },
      { time: 0.3, properties: { rotate: 180, scale: 1.0, opacity: 1 } },
      { time: 0.7, properties: { rotate: 270, scale: 1.0, opacity: 1 } },
      { time: 1.0, properties: { rotate: 360, scale: 0, opacity: 0 } },
    ],
  },
  {
    id: 'color-cycle',
    name: 'Color Cycle',
    description: 'Cycle through hue colors via filter',
    easing: 'linear',
    keyframes: [
      { time: 0, properties: { hueRotate: 0 } },
      { time: 0.25, properties: { hueRotate: 90 } },
      { time: 0.5, properties: { hueRotate: 180 } },
      { time: 0.75, properties: { hueRotate: 270 } },
      { time: 1.0, properties: { hueRotate: 360 } },
    ],
  },
  {
    id: 'wobble',
    name: 'Wobble',
    description: 'Playful wobble back and forth',
    easing: 'ease-in-out',
    keyframes: [
      { time: 0, properties: { rotate: 0, scaleX: 1.0, scaleY: 1.0 } },
      { time: 0.15, properties: { rotate: -15, scaleX: 1.1, scaleY: 0.9 } },
      { time: 0.3, properties: { rotate: 10, scaleX: 0.9, scaleY: 1.1 } },
      { time: 0.45, properties: { rotate: -8, scaleX: 1.05, scaleY: 0.95 } },
      { time: 0.6, properties: { rotate: 4, scaleX: 0.98, scaleY: 1.02 } },
      { time: 0.75, properties: { rotate: -2, scaleX: 1.0, scaleY: 1.0 } },
      { time: 1.0, properties: { rotate: 0, scaleX: 1.0, scaleY: 1.0 } },
    ],
  },
];
