'use client';

import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useStudioStore } from '@/store/store';
import { convertShadertoyShader, extractCustomUniforms } from '@/lib/shadertoy';
import type { ChatMessage, AnimationTemplate, ShaderUniform } from '@/types';

const SYSTEM_PROMPT = `You are an expert GLSL shader programmer. You create shader animations for stock footage websites.

When the user asks for a shader animation, respond with ONLY the GLSL code wrapped in a code block.

Rules:
- Use Shadertoy-compatible format: void mainImage(out vec4 fragColor, in vec2 fragCoord)
- Available uniforms: iTime (float), iResolution (vec2), iFrame (int)
- Create smooth, loopable animations suitable for stock footage
- No interactive elements (no iMouse)
- Aim for visually striking, professional-quality animations
- Include comments explaining the effect
- Output only code in \`\`\`glsl blocks, with brief description before

Example response format:
Here's a smooth gradient wave animation:
\`\`\`glsl
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
  // shader code here
}
\`\`\``;

interface ChatPanelProps {
  onClose: () => void;
}

export function ChatPanel({ onClose }: ChatPanelProps) {
  const {
    chatMessages,
    addChatMessage,
    clearChat,
    chatApiKey,
    setChatApiKey,
    chatModel,
    setChatModel,
    chatProvider,
    setChatProvider,
    setCustomShaderCode,
    setActiveTemplate,
    resetUniformOverrides,
    setActiveTab,
  } = useStudioStore();

  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const extractCodeFromMessage = (content: string): string | null => {
    const codeMatch = content.match(/```(?:glsl|hlsl|c)?\s*\n?([\s\S]*?)```/);
    return codeMatch ? codeMatch[1].trim() : null;
  };

  const handleApplyCode = useCallback(
    (code: string) => {
      const converted = convertShadertoyShader(code);
      setCustomShaderCode(converted);

      const extractedUniforms = extractCustomUniforms(converted);
      const uniforms: ShaderUniform[] = extractedUniforms.map((u) => ({
        name: u.name,
        type: u.type as ShaderUniform['type'],
        value: u.type === 'float' ? 0.5 : 0,
        min: 0,
        max: 5.0,
        step: 0.01,
        label: u.name.replace(/^u_/, '').replace(/_/g, ' '),
      }));

      const template: AnimationTemplate = {
        id: 'ai-' + Date.now(),
        name: 'AI Generated Shader',
        category: 'custom',
        description: 'Generated by AI assistant',
        fragmentShader: converted,
        uniforms,
        duration: 10,
        fps: 30,
      };

      resetUniformOverrides();
      setActiveTemplate(template);
      setActiveTab('editor');
    },
    [setCustomShaderCode, setActiveTemplate, resetUniformOverrides, setActiveTab],
  );

  const handleSend = useCallback(async () => {
    const message = input.trim();
    if (!message || isLoading) return;

    const userMsg: ChatMessage = {
      id: 'msg-' + Date.now(),
      role: 'user',
      content: message,
      timestamp: Date.now(),
    };
    addChatMessage(userMsg);
    setInput('');
    setIsLoading(true);

    try {
      if (!chatApiKey) {
        const assistantMsg: ChatMessage = {
          id: 'msg-' + Date.now() + '-err',
          role: 'assistant',
          content: 'Please set your API key in the settings (gear icon) to use AI chat.',
          timestamp: Date.now(),
        };
        addChatMessage(assistantMsg);
        setShowSettings(true);
        return;
      }

      let response: string;

      if (chatProvider === 'anthropic') {
        response = await callAnthropic(chatApiKey, chatModel, message, chatMessages);
      } else {
        response = await callOpenAI(chatApiKey, chatModel, message, chatMessages);
      }

      const code = extractCodeFromMessage(response);
      const assistantMsg: ChatMessage = {
        id: 'msg-' + Date.now() + '-resp',
        role: 'assistant',
        content: response,
        code: code || undefined,
        timestamp: Date.now(),
      };
      addChatMessage(assistantMsg);

      // Auto-apply if code was generated
      if (code) {
        handleApplyCode(code);
      }
    } catch (err) {
      const errorMsg: ChatMessage = {
        id: 'msg-' + Date.now() + '-err',
        role: 'assistant',
        content: `Error: ${(err as Error).message}`,
        timestamp: Date.now(),
      };
      addChatMessage(errorMsg);
    } finally {
      setIsLoading(false);
    }
  }, [input, isLoading, chatApiKey, chatModel, chatProvider, chatMessages, addChatMessage, handleApplyCode]);

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-studio-border">
        <h2 className="text-sm font-semibold text-studio-text">AI Shader Chat</h2>
        <div className="flex items-center gap-1">
          <button
            onClick={() => setShowSettings(!showSettings)}
            className="p-1.5 rounded hover:bg-white/5 text-studio-text-dim hover:text-studio-text transition-colors"
            title="Settings"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="3" />
              <path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
            </svg>
          </button>
          <button
            onClick={clearChat}
            className="p-1.5 rounded hover:bg-white/5 text-studio-text-dim hover:text-studio-text transition-colors"
            title="Clear chat"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="3 6 5 6 21 6" />
              <path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2" />
            </svg>
          </button>
          <button
            onClick={onClose}
            className="p-1.5 rounded hover:bg-white/5 text-studio-text-dim hover:text-studio-text transition-colors"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      </div>

      {/* Settings */}
      {showSettings && (
        <div className="p-3 border-b border-studio-border bg-studio-bg/50">
          <div className="mb-2">
            <label className="text-xs text-studio-text-dim block mb-1">Provider</label>
            <div className="flex gap-2">
              {['anthropic', 'openai'].map((p) => (
                <button
                  key={p}
                  onClick={() => setChatProvider(p)}
                  className={`flex-1 py-1 text-xs rounded transition-colors ${
                    chatProvider === p
                      ? 'bg-indigo-500/20 border border-indigo-500/40 text-indigo-300'
                      : 'bg-studio-border text-studio-text-dim'
                  }`}
                >
                  {p === 'anthropic' ? 'Anthropic' : 'OpenAI'}
                </button>
              ))}
            </div>
          </div>
          <div className="mb-2">
            <label className="text-xs text-studio-text-dim block mb-1">API Key</label>
            <input
              type="password"
              value={chatApiKey}
              onChange={(e) => setChatApiKey(e.target.value)}
              className="w-full px-2.5 py-1.5 text-xs bg-studio-bg border border-studio-border rounded-lg text-studio-text outline-none focus:border-indigo-500"
              placeholder={chatProvider === 'anthropic' ? 'sk-ant-...' : 'sk-...'}
            />
          </div>
          <div>
            <label className="text-xs text-studio-text-dim block mb-1">Model</label>
            <input
              type="text"
              value={chatModel}
              onChange={(e) => setChatModel(e.target.value)}
              className="w-full px-2.5 py-1.5 text-xs bg-studio-bg border border-studio-border rounded-lg text-studio-text outline-none focus:border-indigo-500"
              placeholder="Model name"
            />
          </div>
        </div>
      )}

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-3 space-y-3">
        {chatMessages.length === 0 && (
          <div className="text-center py-8">
            <p className="text-studio-text-dim text-sm mb-2">
              Describe an animation and AI will generate the shader code
            </p>
            <div className="space-y-1.5">
              {[
                'Create a colorful aurora borealis effect',
                'Make a geometric kaleidoscope pattern',
                'Design flowing liquid metal texture',
                'Create a galaxy spiral with stars',
              ].map((suggestion) => (
                <button
                  key={suggestion}
                  onClick={() => setInput(suggestion)}
                  className="block w-full text-left px-3 py-1.5 text-xs rounded bg-studio-border/50 text-studio-text-dim hover:text-studio-text hover:bg-studio-border transition-colors"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        )}

        {chatMessages.map((msg) => (
          <div key={msg.id}>
            <div
              className={`px-3 py-2 text-sm ${
                msg.role === 'user' ? 'chat-message-user ml-8' : 'chat-message-assistant mr-4'
              }`}
            >
              <div className="whitespace-pre-wrap text-xs leading-relaxed">{msg.content}</div>
            </div>
            {msg.code && (
              <button
                onClick={() => handleApplyCode(msg.code!)}
                className="mt-1 ml-0 px-3 py-1 text-xs rounded bg-indigo-500/20 text-indigo-300 hover:bg-indigo-500/30 transition-colors"
              >
                Apply this shader
              </button>
            )}
          </div>
        ))}

        {isLoading && (
          <div className="chat-message-assistant mr-4 px-3 py-2">
            <div className="flex gap-1">
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce" style={{ animationDelay: '0s' }} />
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce" style={{ animationDelay: '0.15s' }} />
              <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-bounce" style={{ animationDelay: '0.3s' }} />
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-3 border-t border-studio-border">
        <div className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSend();
              }
            }}
            placeholder="Describe an animation..."
            className="flex-1 px-3 py-2 text-sm bg-studio-bg border border-studio-border rounded-lg text-studio-text outline-none focus:border-indigo-500"
          />
          <button
            onClick={handleSend}
            disabled={isLoading || !input.trim()}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              isLoading || !input.trim()
                ? 'bg-studio-border text-studio-text-dim cursor-not-allowed'
                : 'bg-indigo-500 hover:bg-indigo-600 text-white'
            }`}
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}

async function callAnthropic(
  apiKey: string,
  model: string,
  message: string,
  history: ChatMessage[],
): Promise<string> {
  const messages = [
    ...history
      .filter((m) => m.role !== 'system')
      .map((m) => ({
        role: m.role as 'user' | 'assistant',
        content: m.content,
      })),
    { role: 'user' as const, content: message },
  ];

  const res = await fetch('/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      provider: 'anthropic',
      apiKey,
      model,
      system: SYSTEM_PROMPT,
      messages,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(err || `API error: ${res.status}`);
  }

  const data = await res.json();
  return data.content;
}

async function callOpenAI(
  apiKey: string,
  model: string,
  message: string,
  history: ChatMessage[],
): Promise<string> {
  const messages = [
    { role: 'system' as const, content: SYSTEM_PROMPT },
    ...history
      .filter((m) => m.role !== 'system')
      .map((m) => ({
        role: m.role as 'user' | 'assistant',
        content: m.content,
      })),
    { role: 'user' as const, content: message },
  ];

  const res = await fetch('/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      provider: 'openai',
      apiKey,
      model,
      messages,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(err || `API error: ${res.status}`);
  }

  const data = await res.json();
  return data.content;
}
